# Generated by Django 3.0.5 on 2020-04-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_table',
            name='content',
            field=models.TextField(default='you can set default value'),
        ),
    ]
