# Generated by Django 3.0.3 on 2020-04-22 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200422_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_synopsis', models.TextField()),
                ('category_slug', models.CharField(max_length=50)),
                ('category_image', models.ImageField(blank=True, upload_to='main/category/images')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SomeContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='you can set default value')),
                ('published', models.DateTimeField(verbose_name='date name ?')),
                ('context_slug', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SomeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200)),
                ('series_synopsis', models.TextField()),
                ('series_slug', models.CharField(max_length=50)),
                ('series_image', models.ImageField(blank=True, upload_to='main/series/images')),
                ('series_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.SomeCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='new_table',
        ),
        migrations.AddField(
            model_name='somecontext',
            name='context_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.SomeSeries', verbose_name='Series'),
        ),
    ]
