# Generated by Django 3.0.3 on 2020-04-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200423_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='someseries',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='somecategory',
            old_name='category_synopsis',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='somecategory',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='somecategory',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='somecategory',
            old_name='category_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='somecontext',
            old_name='context_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='someseries',
            old_name='series_synopsis',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='someseries',
            old_name='series_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='someseries',
            old_name='series_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='someseries',
            old_name='series_name',
            new_name='title',
        ),
    ]
