# Generated by Django 3.0.3 on 2020-04-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200423_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='someseries',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
