# Generated by Django 3.0.3 on 2020-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200423_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='somecontext',
            name='synopsis',
            field=models.TextField(blank=True, default='you can set default value'),
        ),
        migrations.AlterField(
            model_name='somecontext',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
