# Generated by Django 3.0.3 on 2020-04-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200423_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somecontext',
            name='synopsis',
            field=models.CharField(help_text='yes', max_length=200),
        ),
    ]
