# Generated by Django 3.0.3 on 2020-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200424_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImagesNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/nn/faceclassification/tmp')),
            ],
        ),
    ]
