# Generated by Django 3.0.5 on 2020-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_uploadimagesnn'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_skills', models.TextField()),
                ('education', models.TextField()),
                ('interest', models.TextField()),
                ('experience', models.TextField()),
                ('projects', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
